### ISSUE TITLE
When running the all_code_analysis() method i get an error from the class

### ISSUE THREAD

**Issue by cyber-chimken-nugger** [securisec/glorifiedgrep#2]
Traceback (most recent call last):
  File "gg.py", line 17, in <module>
    code_analysis = g.all_code_analysis()
  File "/home/usr/.local/lib/python3.7/site-packages/glorifiedgrep/android/modules/codeanalysis.py", line 23, in all_code_analysis
    [getattr(self, m)() for m in methods if m not in [
  File "/home/usr/.local/lib/python3.7/site-packages/glorifiedgrep/android/modules/codeanalysis.py", line 23, in <listcomp>
    [getattr(self, m)() for m in methods if m not in [
TypeError: code_imports() missing 1 required positional argument: 'class_name'

**Comment by cyber-chimken-nugger** [comment]
Happens when i try and run the all_code_analysis() method. I can run individual code analysis methods against the apk; when running the "all" function, i get this error. Think its from the class instantiation in the codeanalysis.py file. - where it loops through the var methods.

**Comment by securisec** [comment]
ah, yes, the `all_code_analysis` is a bit deprecated now. I will be removing that in the next version. Thanks for pointing out the issue!
